apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  schedule:
    - cron: "* * * * *"
    - cron: 30 5 * * 1,3
    - cron: 30 5 * * 2,4
    #- cron: "1-59/2 * * * *"
    - cron: "* 9-17 * * *"
    - cron: "* */3 * * *"
    - cron: "0 */2 * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: '* * * * *'
    - cron: '* * * * *'
    - cron: '* * * * *'
    - cron: "* * * * *"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world !"
