apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      param1:
        type: string
        default: value1
      param2:
        type: string
        required: true
      param3:
        type: boolean
        default: false
      param4:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt2
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world !"
