apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  schedule:
    # minutes
    - cron: "5 * * * *"
    - cron: "5,10,15 * * * *"
    - cron: "5-30 * * * *"
    - cron: "30/10 * * * *"
    - cron: "10-50/10 * * * *"
    # hours
    - cron: "* 5 * * *"
    - cron: "* 5,10,15 * * *"
    - cron: "* 5-10 * * *"
    - cron: "* 3/4 * * *"
    - cron: "* 10-20/4 * * *"
    # days
    - cron: "* * 5 * *"
    - cron: "* * 5,10,15 * *"
    - cron: "* * 5-10 * *"
    - cron: "* * 3/4 * *"
    - cron: "* * 10-20/4 * *"
    # months
    - cron: "* * * 5 *"
    - cron: "* * * 5,10,12 *"
    - cron: "* * * 5-10 *"
    - cron: "* * * 3/4 *"
    - cron: "* * * 1-10/4 *"
    # months
    - cron: "* * * 5 *"
    - cron: "* * * */5 *"
    - cron: "* * * 5,10,12 *"
    - cron: "* * * 5-10 *"
    - cron: "* * * 3/4 *"
    - cron: "* * * 2-10/4 *"
    - cron: "* * * MAY *"
    - cron: "* * * JAN,JUN,OCT *"
    - cron: "* * * APR-OCT *"
    - cron: "* * * 4-OCT *"
    - cron: "* * * APR-10 *"
    - cron: "* * * JUL/4 *"
    - cron: "* * * JAN-DEC/4 *"
    - cron: "* * * 1-DEC/4 *"
    - cron: "* * * JAN-12/4 *"
    # days of week
    - cron: "* * * * 5"
    - cron: "* * * * */5"
    - cron: "* * * * 1,3,5"
    - cron: "* * * * 2-5"
    - cron: "* * * * 3/4"
    - cron: "* * * * 0-6/4"
    - cron: "* * * * FRI"
    - cron: "* * * * MON,WED,FRI"
    - cron: "* * * * TUE-SAT"
    - cron: "* * * * 2-SAT"
    - cron: "* * * * TUE-6"
    - cron: "* * * * MON/4"
    - cron: "* * * * MON-FRI/3"
    - cron: "* * * * 1-FRI/3"
    - cron: "* * * * MON-5/3"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world !"
