apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      param1:
        type: string
        default: |-
          string1
          string2
          string3
          string4
      param2:
        type: choice
        options:
          - option 1
          - option 2
          - option3
        default: option 2
      param3:
        type: boolean
        default: true
      param4:
        type: number
        default: 12345
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world !"
