apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  schedule:
    # minutes
    - cron: "5 * * * *"
    - cron: "5,10,15 * * * *"
    - cron: "5-30 * * * *"
    - cron: "30/10 * * * *"
    - cron: "10-50/10 * * * *"
    # hours
    - cron: "* 5 * * *"
    - cron: "* 5,10,15 * * *"
    - cron: "* 5-10 * * *"
    - cron: "* 3/4 * * *"
    - cron: "* 10-20/4 * * *"
    # days
    - cron: "* * 5 * *"
    - cron: "* * 5,10,15 * *"
    - cron: "* * 5-10 * *"
    - cron: "* * 3/4 * *"
    - cron: "* * 10-20/4 * *"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world !"
