apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  schedule:
    - cron: "* * * * *"
    - cron: 30-1 5 * * 1,3
    - cron: 30 5 * * 2,4
    - cron: "9 * 1-4/3 * *"
    - cron: "* 9-17 * * *"
    - cron: "* 1/3 * * *"
    - cron: "0 2/2 * * *"
    - cron: "* * */3 * *"
    #- cron: "* * * */2 *"
    - cron: "0 0 1 1 *"
    - cron: "0 22 * * 1-5"
    #- cron: "23 0-20/2 * * *"
    - cron: "0 0,12 1 2 *"
    - cron: "0 4 8-14/3 * *"
    - cron: "* * 3/3 * *"
    #- cron: "5 4 14 */3 *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: "* * * * *"
    - cron: '* * * * *'
    - cron: '* * * * *'
    - cron: '* * * * *'
    - cron: "* * * * *"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world !"
